server:
  port: 8888
  ssl:
    enabled: false
    bundle: "secureme-config"
    enabled-protocols: TLSv1.3
spring:
  ssl:
    enabled: true
    bundle:
      jks:
        secureme-config:
          key:
            alias: "secureme-config"
          keystore:
            location: "classpath:secureme-config.jks"
            password: "secureme-config"
            type: "JKS"
            provider: "SUN"
          truststore:
            location: "classpath:secureme-config.jks"
            password: "secureme-config"
            type: "JKS"
  cloud:
    config:
      server:
        native:
          search-locations:
          - file:///C:/My WorkSpace/Hire_Me_Workspace/SecureMe_Configuration_Properties
  profiles:
    active:
    - native
  security:
    user:
      name: config
      password: config
