server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          search-locations:
          - file:///C:/My WorkSpace/Hire_Me_Workspace/SecureMe_Configuration_Properties
  profiles:
    active:
    - native
  security:
    user:
      name: config
      password: config
